import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import NavMenu from "@/components/NavMenu";
import SessionProvider from "@/components/AuthProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900 w-screen h-screen  text-gray-50`}>
        <SessionProvider session={session}>
          <div className="fixed h-20 left-1/2 py-4">
            <NavMenu />
          </div>
          <div className="pt-32 flex flex-col justify-center items-center w-full h-full  ">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
